blueprint:
  name: Zigbee2MQTT - Tuya 2-Button Switch (MQTT Subscribe Any - Filters Multiple Devices) - rdeangel
  description: >
    Blueprint Version: 11-01-25

    Blueprint Name: Zigbee2MQTT - Tuya 2-Button Switch (MQTT Subscribe Any - Filters Multiple Devices) - rdeangel

    This blueprint subscribes to all MQTT messages on the topic `zigbee2mqtt/+/action` and then filters the correct device based on your selection.
    It allows one blueprint to be used for multiple 2-button controllers. The blueprint evaluates whether the received MQTT message belongs
    to the selected device(s) and if so, executes the corresponding action based on the payload (e.g. `1_single`, `2_double`, etc.).

    If you only need one device, simply select one. If you have multiple identical controllers, you can select more than one.
  domain: automation
  input:
    mode:
      name: Automation Mode
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
          multiple: false
          custom_value: false
          sort: false

    zigbee_device:
      name: Zigbee Devices - Tuya TS0042 (and alike)
      description: Select one or more devices corresponding to the 2-button controller (TS0042).
      selector:
        device:
          integration:
            domain: mqtt
          multiple: true

    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on Button 1 (short press)
      default: []
      selector:
        action: {}

    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on Button 1 (double press)
      default: []
      selector:
        action: {}

    button_one_long_press:
      name: Long Press - Button 1
      description: Action to run on Button 1 (long press)
      default: []
      selector:
        action: {}

    button_two_short_press:
      name: Single Press - Button 2
      description: Action to run on Button 2 (short press)
      default: []
      selector:
        action: {}

    button_two_double_press:
      name: Double Press - Button 2
      description: Action to run on Button 2 (double press)
      default: []
      selector:
        action: {}

    butto
